#import "@preview/elembic:1.1.1" as e

#import "text.typ": xl, lg, md, sm
#import "../utils.typ": PREFIX

#let page-settings = e.types.declare(
  "page-settings",
  prefix: PREFIX,
  doc: "template page settings",
  fields: (
    e.field("paper", str, default: "presentation-16-9",
      doc: "standard paper size"),
    e.field("width", e.types.union(auto, length), default: auto,
      doc: "page width"),
    e.field("height", e.types.union(auto, length), default: auto,
      doc: "page height"),
    e.field("flipped", bool, default: false,
      doc: "landscape orientation"),
    e.field("margin", e.types.union(auto, relative, dictionary), default: (x: 0.5in, y: 0.2in),
      doc: "page margins"),
    e.field("bleed", e.types.union(auto, relative, dictionary), default: (:),
      doc: "page bleed margins"),
    e.field("binding", e.types.union(auto, alignment), default: auto,
      doc: "page binding side"),
    e.field("columns", int, default: 1,
      doc: "number of page columns"),
    e.field("fill", e.types.union(none, auto, color, gradient, tiling), default: auto,
      doc: "page background fill"),
    e.field("numbering", e.types.union(none, str, function), default: none,
      doc: "page numbering"),
    e.field("supplement", e.types.union(none, auto, content), default: auto,
      doc: "page supplement"),
    e.field("number-align", alignment, default: left + top,
      doc: "page numbering alignment"),
    e.field("header", e.types.union(none, auto, content), default: auto,
      doc: "page header in top margin"),
    e.field("header-ascent", relative, default: 25% + 0pt,
      doc: "header spacing above main area"),
    e.field("footer", e.types.union(none, auto, content), default: auto,
      doc: "page footer in bottom margin"),
    e.field("footer-descent", relative, default: 25% + 0pt,
      doc: "footer spacing below main area"),
    e.field("background", e.types.union(none, content), default: none,
      doc: "page background content"),
    e.field("foreground", e.types.union(none, content), default: none,
      doc: "page foreground content"),
  ),
)

#let text-settings = e.types.declare(
  "text-settings",
  prefix: PREFIX,
  doc: "template text settings",
  fields: (
    e.field("font", e.types.union(str, array, dictionary), default: "Excalifont"),
    e.field("fallback", bool, default: true),
    e.field("style", str, default: "normal"),
    e.field("weight", e.types.union(int, str), default: "regular"),
    e.field("stretch", ratio, default: 100%),
    e.field("size", length, default: lg),
    e.field("fill", e.types.paint, default: black),
    e.field(
      "stroke",
      e.types.union(
        none,
        length,
        color,
        gradient,
        stroke,
        tiling,
        dictionary,
      ),
      default: none,
    ),
    e.field("tracking", length, default: 0pt),
    e.field("spacing", relative, default: 100% + 0pt),
    e.field("cjk-latin-spacing", e.types.option(auto), default: auto),
    e.field("baseline", length, default: 0pt),
    e.field("overhang", bool, default: true),
    e.field("top-edge", e.types.union(length, str), default: "cap-height"),
    e.field("bottom-edge", e.types.union(length, str), default: "baseline"),
    e.field("lang", str, default: "en"),
    e.field("region", e.types.option(str), default: none),
    e.field("script", e.types.smart(str), default: auto),
    e.field("dir", e.types.smart(direction), default: auto),
    e.field("hyphenate", e.types.smart(bool), default: auto),
    e.field("costs", dictionary, default: (:)),
    e.field("kerning", bool, default: true),
    e.field("alternates", e.types.union(bool, int), default: false),
    e.field("stylistic-set", e.types.union(none, int, array), default: none),
    e.field("ligatures", bool, default: true),
    e.field("discretionary-ligatures", bool, default: false),
    e.field("historical-ligatures", bool, default: false),
    e.field("number-type", e.types.smart(str), default: auto),
    e.field("number-width", e.types.smart(str), default: auto),
    e.field("slashed-zero", bool, default: false),
    e.field("fractions", bool, default: false),
    e.field("features", e.types.union(array, dictionary), default: (:)),
    e.field("variations", dictionary, default: (:)),
  ),
)

#let raw-settings = e.types.declare(
  "raw-settings",
  prefix: PREFIX,
  doc: "template raw block settings",
  fields: (
    e.field("block", bool, default: false),
    e.field("lang", e.types.option(str), default: none),
    e.field("align", alignment, default: start),
    e.field("syntaxes", e.types.union(str, path, bytes, array), default: ()),
    e.field("theme", e.types.union(none, auto, str, path, bytes), default: auto),
    e.field("tab-size", int, default: 2),
  ),
)

#let codly-settings = e.types.declare(
  "codly-settings",
  prefix: PREFIX,
  doc: "template codly settings",
  fields: (
    e.field("enabled", e.types.union(bool, function), default: true,
      doc: "Whether Codly styling is enabled. A function can determine this dynamically for each code block."),
    e.field("header", e.types.union(content, none, function), default: none,
      doc: "Content displayed as a header above the code block, or a function that generates it."),
    e.field("header-repeat", e.types.union(bool, function), default: false,
      doc: "Whether the header is repeated when a code block continues across pages."),
    e.field("header-cell-args", e.types.union(array, dictionary, arguments, function), default: (),
      doc: "Additional arguments applied to the table cell containing the header."),
    e.field("header-transform", function, default: it => it,
      doc: "A function that transforms the generated header content before it is displayed."),
    e.field("footer", e.types.union(content, none, function), default: none,
      doc: "Content displayed as a footer below the code block, or a function that generates it."),
    e.field("footer-repeat", e.types.union(bool, function), default: false,
      doc: "Whether the footer is repeated when a code block continues across pages."),
    e.field("footer-cell-args", e.types.union(array, dictionary, arguments, function), default: (),
      doc: "Additional arguments applied to the table cell containing the footer."),
    e.field("footer-transform", function, default: it => it,
      doc: "A function that transforms the generated footer content before it is displayed."),
    e.field("offset", e.types.union(int, function), default: 0,
      doc: "The offset added to displayed line numbers."),
    e.field("offset-from", e.types.union(none, label, function), default: none,
      doc: "A labeled code block whose final line number is used as the numbering offset."),
    e.field("range", e.types.union(none, array, function), default: none,
      doc: "A range selecting which lines of the code block are displayed."),
    e.field("ranges", e.types.union(none, array, function), default: none,
      doc: "Multiple ranges selecting which portions of the code block are displayed."),
    e.field("smart-skip", e.types.union(bool, dictionary, function), default: false,
      doc: "Controls automatic collapsing of omitted lines between displayed ranges."),
    e.field("languages", e.types.union(dictionary, function), default: (:),
      doc: "Language metadata used for names, icons, colors, and aliases."),
    e.field("default-color", e.types.union(color, gradient, tiling, function), default: blue,
      doc: "Fallback accent color used when the code block's language has no configured color."),
    e.field("radius", e.types.union(length, function), default: 0.32em,
      doc: "Corner radius of the code block container."),
    e.field("inset", e.types.union(length, dictionary, function), default: 0.32em,
      doc: "Inner spacing between the code and the edges of the code block."),
    e.field("fill", e.types.union(none, color, gradient, tiling, function), default: none,
      doc: "Background paint of the code block."),
    e.field("zebra-fill", e.types.union(none, color, gradient, tiling, function), default: none,
      doc: "Background paint applied to alternating code lines."),
    e.field("stroke", e.types.union(none, stroke, function), default: 1pt + luma(240),
      doc: "Border drawn around the code block."),
    e.field("lang-inset", e.types.union(length, dictionary, function), default: 0.32em,
      doc: "Inner spacing of the language label displayed with the code block."),
    e.field("lang-outset", e.types.union(dictionary, function), default: (x: 0.32em, y: 0em),
      doc: "Amount by which the language label extends beyond its normal bounds."),
    e.field("lang-radius", e.types.union(length, function), default: 0.32em,
      doc: "Corner radius of the language label."),
    e.field("lang-stroke", e.types.union(none, stroke, function), default: lang => lang.color + 0.5pt,
      doc: "Border drawn around the language label."),
    e.field("lang-fill", e.types.union(none, color, gradient, tiling, function), default: lang => lang.color.lighten(80%),
      doc: "Background paint of the language label."),
    e.field("lang-format", e.types.union(auto, none, function), default: auto,
      doc: "Function used to construct the language label, `auto` for Codly's default, or `none` to hide it."),
    e.field("display-name", bool, default: true,
      doc: "Whether the configured language name is shown in the language label."),
    e.field("display-icon", bool, default: true,
      doc: "Whether the configured language icon is shown in the language label."),
    e.field("number-format", e.types.union(function, none), default: numbering.with("1"),
      doc: "Function that converts each line number into displayed content, or `none` to hide line numbers."),
    e.field("number-align", e.types.union(alignment, function), default: left + horizon,
      doc: "Alignment of line numbers within the numbering column."),
    e.field("number-placement", str, default: "inside",
      doc: "Side of the code block on which line numbers are placed."),
    e.field("smart-indent", bool, default: true,
      doc: "Whether common leading indentation is removed from displayed code."),
    e.field("skip-last-empty", bool, default: true,
      doc: "Whether a trailing empty line in the raw code block is omitted."),
    e.field("breakable", bool, default: true,
      doc: "Whether the code block may break across pages."),
    e.field("skips", e.types.union(array, none), default: none,
      doc: "Line ranges that are replaced by skip indicators."),
    e.field("skip-line", e.types.union(content, none), default: align(center)[ ... ],
      doc: "Content displayed in the code area for a collapsed group of lines."),
    e.field("skip-number", e.types.union(content, none), default: [ ... ],
      doc: "Content displayed in the numbering column for a collapsed group of lines."),
    e.field("annotations", e.types.union(array, none), default: none,
      doc: "Annotations attached to selected lines or ranges of the code block."),
    e.field("annotation-format", e.types.union(none, function), default: numbering.with("(1)"),
      doc: "Function that formats annotation markers and annotation content."),
    e.field("highlighted-lines", e.types.union(array, none, function), default: (),
      doc: "Lines or line ranges that receive the default line highlight."),
    e.field("highlighted-default-color", e.types.union(color, tiling, gradient), default: orange.lighten(60%),
      doc: "Default paint used for entries in `highlighted-lines`."),
    e.field("highlights", e.types.union(array, none), default: none,
      doc: "Custom token or character ranges to highlight within the code."),
    e.field("highlight-radius", length, default: 0.32em,
      doc: "Corner radius of custom highlight regions."),
    e.field("highlight-fill", function, default: color => color.lighten(80%),
      doc: "Function that determines the background paint of each custom highlight."),
    e.field("highlight-stroke", e.types.union(stroke, function), default: color => 0.5pt + color,
      doc: "Border applied to custom highlight regions."),
    e.field("highlight-inset", e.types.union(length, dictionary), default: 0.32em,
      doc: "Inner expansion or spacing applied to custom highlight regions."),
    e.field("highlight-outset", e.types.union(length, dictionary), default: 0.32em,
      doc: "Outer expansion applied around custom highlight regions."),
    e.field("highlight-clip", bool, default: true,
      doc: "Whether custom highlights are clipped to the bounds of the code block."),
    e.field("reference-by", str, default: "line",
      doc: "Attribute by which labeled code blocks are referenced."),
    e.field("reference-sep", e.types.union(str, content), default: "-",
      doc: "Separator placed between the code-block reference name and its number."),
    e.field("reference-number-format", function, default: numbering.with("1"),
      doc: "Function that formats the number displayed by a reference to the code block."),
    e.field("aliases", dictionary, default: (:),
      doc: "Alternative language identifiers mapped to their canonical language identifiers."),
  ),
)
