#import "@preview/oxifmt:1.0.0": strfmt

/// available syntax highlighting themes
#let tm-themes = {
  (
    "andromeeda",
    "aurora-x",
    "ayu-dark",
    "ayu-light",
    "ayu-mirage",
    "catppuccin-frappe",
    "catppuccin-latte",
    "catppuccin-macchiato",
    "catppuccin-mocha",
    "dark-plus",
    "dracula-soft",
    "dracula",
    "everforest-dark",
    "everforest-light",
    "github-dark-default",
    "github-dark-dimmed",
    "github-dark-high-contrast",
    "github-dark",
    "github-light-default",
    "github-light-high-contrast",
    "github-light",
    "gruvbox-dark-hard",
    "gruvbox-dark-medium",
    "gruvbox-dark-soft",
    "gruvbox-light-hard",
    "gruvbox-light-medium",
    "gruvbox-light-soft",
    "horizon-bright",
    "horizon",
    "houston",
    "kanagawa-dragon",
    "kanagawa-lotus",
    "kanagawa-wave",
    "laserwave",
    "light-plus",
    "material-theme-darker",
    "material-theme-lighter",
    "material-theme-ocean",
    "material-theme-palenight",
    "material-theme",
    "min-dark",
    "min-light",
    "monokai",
    "night-owl-light",
    "night-owl",
    "nord",
    "one-dark-pro",
    "one-light",
    "plastic",
    "poimandres",
    "red",
    "rose-pine-dawn",
    "rose-pine-moon",
    "rose-pine",
    "slack-dark",
    "slack-ochin",
    "snazzy-light",
    "solarized-dark",
    "solarized-light",
    "synthwave-84",
    "tokyo-night",
    "vesper",
    "vitesse-black",
    "vitesse-dark",
    "vitesse-light",
  ).map(name => {
    let theme-path = strfmt("../assets/tm-themes/{}.tmTheme", name)
    let theme-data = read(theme-path, encoding: none)
    (name, theme-data)
  }).to-dict()
}
